export const Books = [
    {
        id: 1,
        title: 'Jane Eyre',
        author: 'Charollete Bronte',
        publishedDate: 1949,
        category: "Classic",
        description: "Jane Eyre is a first-person narrative told from the perspective of Jane, a seemingly 'plain' girl who meets a lot of challenges in life.",
        coverImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRugZtaqg69K9P0r0QQhJZ1inH--ObMEzdv9Q&s",
        ratings: 4.3,
    },

    {
        id: 2,
        title: 'Pride and Prejudice',
        author: 'Jane Austen',
        publishedDate: 1951,
        category: "Classic",
        description: "A classic novel exploring themes of love, marriage, and social norms.",
        coverImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRqF3gUdYgQwPkHYklsejjfIh7-B5gLMMlo6g&s",
        ratings: 4.2,
    },
    {
        id: 3,
        title: 'Emma',
        author: 'Jane Austen',
        publishedDate: 1960,
        category: "Fiction",
        description: "It is set in the fictional country village of Highbury and the surrounding estates of Hartfield, Randalls and Donwell Abbey, and involves the relationships among people from a small number of families.",
        coverImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSc7GO681OgSLg2c_yVA5xIwwX9zUJfPzb3Kw&s",
        ratings: 4.7,
    },

    {
        id: 4,
        title: 'Walk Into The Shadow',
        author: 'Mike Ricksecker',
        publishedDate: 1970,
        category: "Mystery",
        description: "Shadow people are some of the most mysterious entities in the known universe, and Mike Ricksecker has experienced many, starting with a tall, dark humanoid figure that appeared in his room as a child.",
        coverImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRZ1K_Y8KVyiu2GbBwKQix-8Bi7yhDsxOQBUw&s",
        ratings: 4.0,
    },

    {
        id: 5,
        title: 'Soul',
        author: 'Olivia Wilson',
        publishedDate: 1955,
        category: "Sci-Fi",
        description: "The attempt to connect the field of neuroscience with the spiritual lessons found in the Bible in order to provide holistic care for an individual",
        coverImage: "https://marketplace.canva.com/EAFaQMYuZbo/1/0/1003w/canva-brown-rusty-mystery-novel-book-cover-hG1QhA7BiBU.jpg",
        ratings: 4.9,
    },

    {
        id: 6,
        title: 'Alone',
        author: 'Megan E. Freeman',
        publishedDate: 1999,
        category: "Fiction",
        description: "When twelve-year-old Maddie hatches a scheme for a secret sleepover with her two best friends, she ends up waking up to a nightmare.",
        coverImage: "https://marketplace.canva.com/EAFPHUaBrFc/1/0/1003w/canva-black-and-white-modern-alone-story-book-cover-QHBKwQnsgzs.jpg",
        ratings: 4.8,
    },

    {
        id: 7,
        title: 'Hide And Seek',
        author: 'Olivia Wilson',
        publishedDate: 2001,
        category: "Mystery",
        description: "The story revolves around the disappearance of 3 year old Lily Murphy and the connection it has to Joanna Stedman who now lives in her house",
        coverImage: "https://marketplace.canva.com/EAFf0E5urqk/1/0/1003w/canva-blue-and-green-surreal-fiction-book-cover-53S3IzrNxvY.jpg",
        ratings: 3.9,
    },

    {
        id: 8,
        title: 'Memory',
        author: 'Mahesh Dattani',
        publishedDate: 1970,
        category: "Mystery",
        description: "The Memory Book is about a woman named Claire who is going through early-onset Alzheimers.",
        coverImage: "https://d1csarkz8obe9u.cloudfront.net/posterpreviews/contemporary-fiction-night-time-book-cover-design-template-1be47835c3058eb42211574e0c4ed8bf_screen.jpg?ts=1698210220",
        ratings: 4.1,
    },

    {
        id: 9,
        title: 'Macbeth',
        author: 'Macbeth',
        publishedDate: 1977,
        category: "Fiction",
        description: "It is thought to have been first performed in 1606. It dramatises the damaging physical and psychological effects of political ambition on those who seek power.",
        coverImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSvk3ZBhvKfqwiBdwNBGAlY1HOtzCFAN_eIiw&s",
        ratings: 5.0,
    },

    {
        id: 10,
        title: 'Frankenstein',
        author: 'Mary Shelley',
        publishedDate: 1980,
        category: "Sci-Fi",
        description: "Frankenstein tells the story of Victor Frankenstein, a young scientist who creates a sapient creature in an unorthodox scientific experiment.",
        coverImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSfqAMhLJRKNhQnT2KSIxN5IqjWsGrDDv7ppg&s",
        ratings: 4.4,
    },
    {
        id: 11,
        title: "To Kill a Mockingbird",
        author: "Harper Lee",
        publishedDate: 1960,
        category: "Classic",
        description: "A classic novel depicting racial injustice in the American South.",
        coverImage: "https://rukminim2.flixcart.com/image/850/1000/xif0q/book/7/2/p/to-kill-a-mockingbird-original-imahy8w3zudfys7s.jpeg?q=20&crop=false",
        ratings: 4.2,
    },
    {
        id: 12,
        title: "1984",
        author: "George Orwell",
        publishedDate: 1949,
        category: "Sci-Fi",
        description: "A dystopian novel portraying a totalitarian society.",
        coverImage: "https://m.media-amazon.com/images/I/51BIA4rraeL._AC_UF1000,1000_QL80_.jpg",
        ratings: 4.9,
    },
    {
        id: 13,
        title: "The Great Gatsby",
        author: "F. Scott Fitzgerald",
        publishedDate: 1925,
        category: "Classic",
        description: "A tale of the American Dream, wealth, and love during the Roaring Twenties.",
        coverImage: "https://d28hgpri8am2if.cloudfront.net/book_images/onix/cvr9781524879761/the-great-gatsby-9781524879761_hr.jpg",
        ratings: 4.3,
    },
    {
        id: 14,
        title: "The Catcher in the Rye",
        author: "J.D. Salinger",
        publishedDate: 1951,
        category: "Fiction",
        description: "A classic coming-of-age novel following Holden Caulfield's journey.",
        coverImage: "https://rukminim2.flixcart.com/image/850/1000/kufuikw0/book/p/a/q/the-catcher-in-the-rye-original-imag7jttju9vfuxa.jpeg?q=20&crop=false",
        ratings: 3.7,
    },
    {
        id: 15,
        title: "Slaughterhouse-Five",
        author: "Kurt Vonnegut",
        publishedDate: 1969,
        category: "Sci-Fi",
        description: "An anti-war novel that mixes science fiction and dark humor.",
        coverImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3c6GD18Bp1Wf38aR0LAgEhN7Ze8siJOKKjg&s",
        ratings: 4.1,
      },
];